// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-companies.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(value) {
  return { content: [{ type: "text", text: JSON.stringify(value) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-companies.ts
var list_companies_default = defineTool({
  name: "list_companies",
  title: "\uC5C5\uCCB4 \uBAA9\uB85D \uC870\uD68C",
  description: "\uB85C\uADF8\uC778\uD55C \uC0AC\uC6A9\uC790\uC758 \uAC70\uB798 \uC5C5\uCCB4(\uD68C\uC0AC) \uBAA9\uB85D\uACFC \uC815\uC0B0 \uC124\uC815(\uC138\uAE08\uACC4\uC0B0\uC11C \uBC1C\uD589/\uBD80\uAC00\uC138 \uD3EC\uD568/\uC815\uC0B0\uC8FC\uAE30/\uC694\uC728)\uC744 \uC870\uD68C\uD569\uB2C8\uB2E4.",
  inputSchema: {
    active_only: z.boolean().optional().describe("\uD65C\uC131 \uC5C5\uCCB4\uB9CC \uC870\uD68C\uD560\uC9C0 \uC5EC\uBD80. \uAE30\uBCF8\uAC12 true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let q = supabaseForUser(ctx).from("companies").select("id,name,active,issues_invoice,vat_included,settlement_cycle,fee_rate_metro,fee_rate_regional,has_cod,account_number").order("name");
    if (active_only !== false) q = q.eq("active", true);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return { ...textResult(data ?? []), structuredContent: { companies: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-leaders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_leaders_default = defineTool2({
  name: "list_team_leaders",
  title: "\uD300\uC7A5 \uBAA9\uB85D \uC870\uD68C",
  description: "\uB85C\uADF8\uC778\uD55C \uC0AC\uC6A9\uC790\uC758 \uBC30\uC1A1 \uD300\uC7A5(\uAE30\uC0AC) \uBAA9\uB85D\uC744 \uC870\uD68C\uD569\uB2C8\uB2E4.",
  inputSchema: {
    active_only: z2.boolean().optional().describe("\uD65C\uC131 \uD300\uC7A5\uB9CC \uC870\uD68C\uD560\uC9C0 \uC5EC\uBD80. \uAE30\uBCF8\uAC12 true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let q = supabaseForUser(ctx).from("team_leaders").select("*").order("name");
    if (active_only !== false) q = q.eq("active", true);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return { ...textResult(data ?? []), structuredContent: { leaders: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-deliveries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_deliveries_default = defineTool3({
  name: "list_deliveries",
  title: "\uBC30\uC1A1 \uAE30\uB85D \uC870\uD68C",
  description: "\uAE30\uAC04/\uC5C5\uCCB4/\uD300\uC7A5 \uC870\uAC74\uC73C\uB85C \uBC30\uC1A1 \uAE30\uB85D\uC744 \uC870\uD68C\uD569\uB2C8\uB2E4. \uB0A0\uC9DC\uB294 YYYY-MM-DD \uD615\uC2DD\uC785\uB2C8\uB2E4.",
  inputSchema: {
    from: z3.string().optional().describe("\uC2DC\uC791 \uB0A0\uC9DC (YYYY-MM-DD, \uD3EC\uD568)."),
    to: z3.string().optional().describe("\uC885\uB8CC \uB0A0\uC9DC (YYYY-MM-DD, \uD3EC\uD568)."),
    company_name: z3.string().optional().describe("\uC5C5\uCCB4\uBA85 \uBD80\uBD84 \uC77C\uCE58 \uD544\uD130."),
    leader_name: z3.string().optional().describe("\uD300\uC7A5\uBA85 \uBD80\uBD84 \uC77C\uCE58 \uD544\uD130 (1\uBC88 \uD300\uC7A5 \uAE30\uC900)."),
    limit: z3.number().optional().describe("\uCD5C\uB300 \uBC18\uD658 \uD589 \uC218. \uAE30\uBCF8 100, \uCD5C\uB300 500.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, company_name, leader_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const max = Math.min(Math.max(Math.trunc(limit ?? 100), 1), 500);
    let q = supabaseForUser(ctx).from("deliveries").select(
      "id,date,company_name,leader1_name,leader2_name,leader3_name,customer_name,region,item,note,metro_fee,note_amount,regional_fee,cod_amount,paid,two_person,split_type"
    ).order("date", { ascending: false }).limit(max);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (company_name) q = q.ilike("company_name", `%${company_name}%`);
    if (leader_name) q = q.ilike("leader1_name", `%${leader_name}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return { ...textResult(data ?? []), structuredContent: { rows: data ?? [], count: data?.length ?? 0 } };
  }
});

// src/lib/mcp/tools/settlement-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var settlement_summary_default = defineTool4({
  name: "settlement_summary",
  title: "\uAE30\uAC04 \uC815\uC0B0 \uC694\uC57D",
  description: "\uC9C0\uC815\uD55C \uAE30\uAC04\uC758 \uBC30\uC1A1\uBE44 \uD569\uACC4\uB97C \uC5C5\uCCB4\uBCC4/\uD300\uC7A5\uBCC4\uB85C \uC9D1\uACC4\uD569\uB2C8\uB2E4. \uCC29\uBD88(cod)\uC740 \uBCF4\uACE0\uC6A9\uC73C\uB85C \uBCC4\uB3C4 \uD45C\uC2DC\uB418\uBA70 \uBC30\uC1A1\uBE44 \uD569\uACC4\uC5D0\uB294 \uD3EC\uD568\uB418\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.",
  inputSchema: {
    from: z4.string().describe("\uC2DC\uC791 \uB0A0\uC9DC (YYYY-MM-DD, \uD3EC\uD568)."),
    to: z4.string().describe("\uC885\uB8CC \uB0A0\uC9DC (YYYY-MM-DD, \uD3EC\uD568)."),
    group_by: z4.string().optional().describe("\uC9D1\uACC4 \uAE30\uC900: 'company' \uB610\uB294 'leader'. \uAE30\uBCF8 'company'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, group_by }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const key = group_by === "leader" ? "leader1_name" : "company_name";
    const { data, error } = await supabaseForUser(ctx).from("deliveries").select("company_name,leader1_name,metro_fee,note_amount,regional_fee,cod_amount").gte("date", from).lte("date", to);
    if (error) return errorResult(error.message);
    const acc = /* @__PURE__ */ new Map();
    for (const r of data ?? []) {
      const name = r[key] || "(\uBBF8\uC9C0\uC815)";
      const cur = acc.get(name) ?? { name, count: 0, delivery_fee: 0, cod: 0 };
      cur.count += 1;
      cur.delivery_fee += Number(r.metro_fee ?? 0) + Number(r.note_amount ?? 0) + Number(r.regional_fee ?? 0);
      cur.cod += Number(r.cod_amount ?? 0);
      acc.set(name, cur);
    }
    const groups = [...acc.values()].sort((a, b) => b.delivery_fee - a.delivery_fee);
    const total = groups.reduce((s, g) => s + g.delivery_fee, 0);
    const payload = { from, to, group_by: key === "leader1_name" ? "leader" : "company", total_delivery_fee: total, groups };
    return { ...textResult(payload), structuredContent: payload };
  }
});

// src/lib/mcp/tools/create-delivery.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var create_delivery_default = defineTool5({
  name: "create_delivery",
  title: "\uBC30\uC1A1 \uAE30\uB85D \uCD94\uAC00",
  description: "\uC0C8 \uBC30\uC1A1 \uAE30\uB85D\uC744 \uCD94\uAC00\uD569\uB2C8\uB2E4. \uAE08\uC561\uC740 \uC6D0 \uB2E8\uC704 \uC22B\uC790\uC785\uB2C8\uB2E4.",
  inputSchema: {
    date: z5.string().describe("\uBC30\uC1A1 \uB0A0\uC9DC (YYYY-MM-DD)."),
    company_name: z5.string().describe("\uC5C5\uCCB4\uBA85."),
    leader1_name: z5.string().optional().describe("\uBC30\uC1A1 \uD300\uC7A5\uBA85."),
    customer_name: z5.string().optional().describe("\uACE0\uAC1D\uBA85."),
    region: z5.string().optional().describe("\uBC30\uC1A1 \uC9C0\uC5ED/\uC8FC\uC18C."),
    item: z5.string().optional().describe("\uD488\uBAA9."),
    note: z5.string().optional().describe("\uBE44\uACE0."),
    metro_fee: z5.number().optional().describe("\uC218\uB3C4\uAD8C \uBC30\uC1A1\uBE44."),
    regional_fee: z5.number().optional().describe("\uC9C0\uBC29 \uBC30\uC1A1\uBE44."),
    note_amount: z5.number().optional().describe("\uBE44\uACE0 \uAE08\uC561."),
    cod_amount: z5.number().optional().describe("\uCC29\uBD88 \uAE08\uC561 (\uBCF4\uACE0\uC6A9, \uC5C5\uCCB4 \uCCAD\uAD6C\uC5D0\uB294 \uBBF8\uD3EC\uD568).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const sb = supabaseForUser(ctx);
    const { data: company } = await sb.from("companies").select("id,name").ilike("name", input.company_name).maybeSingle();
    const { data: leader } = input.leader1_name ? await sb.from("team_leaders").select("id,name").ilike("name", input.leader1_name).maybeSingle() : { data: null };
    const { data, error } = await sb.from("deliveries").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      company_id: company?.id ?? null,
      company_name: company?.name ?? input.company_name,
      leader1_id: leader?.id ?? null,
      leader1_name: leader?.name ?? input.leader1_name ?? null,
      customer_name: input.customer_name ?? null,
      region: input.region ?? null,
      item: input.item ?? null,
      note: input.note ?? null,
      metro_fee: input.metro_fee ?? 0,
      regional_fee: input.regional_fee ?? 0,
      note_amount: input.note_amount ?? 0,
      cod_amount: input.cod_amount ?? 0
    }).select().single();
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { row: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "opqsvhgymwbaagvwjiul";
var mcp_default = defineMcp({
  name: "settled-up",
  title: "\uC815\uC0B0\uC758 \uB2EC\uC778",
  version: "0.1.0",
  instructions: "\uAC00\uAD6C/\uCE68\uB300 \uBC30\uC1A1 \uC815\uC0B0 \uC571\uC758 \uB3C4\uAD6C \uBAA8\uC74C\uC785\uB2C8\uB2E4. \uC5C5\uCCB4\xB7\uD300\uC7A5 \uBAA9\uB85D \uC870\uD68C, \uAE30\uAC04\uBCC4 \uBC30\uC1A1 \uAE30\uB85D \uC870\uD68C, \uC5C5\uCCB4/\uD300\uC7A5\uBCC4 \uC815\uC0B0 \uC694\uC57D \uC9D1\uACC4, \uBC30\uC1A1 \uAE30\uB85D \uCD94\uAC00\uB97C \uC9C0\uC6D0\uD569\uB2C8\uB2E4. \uCC29\uBD88(cod) \uAE08\uC561\uC740 \uBCF4\uACE0\uC6A9\uC774\uBA70 \uC5C5\uCCB4 \uCCAD\uAD6C \uAE08\uC561\uC5D0 \uD3EC\uD568\uB418\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_companies_default, list_leaders_default, list_deliveries_default, settlement_summary_default, create_delivery_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
